Repository Cairo-Squad/Movio, pull requests merged in 2025-07, with the labels that each got.

#12 component/app-bar
  design_system/src/main/java/com/cairosquad/design_system/component/AppBar.kt
  design_system/src/main/res/drawable/arrow_left_icon_round.xml
  design_system/src/main/res/drawable/heart_icon_round.xml
  design_system/src/main/res/drawable/share_icon_round.xml
  design_system/src/main/res/values-ar-rEG/strings.xml
  design_system/src/main/res/values/strings.xml
Labels: component

#13 Component/top bar
  design_system/src/main/java/com/cairosquad/design_system/color/MovioColors.kt
  design_system/src/main/java/com/cairosquad/design_system/color/darkThemeColors.kt
  design_system/src/main/java/com/cairosquad/design_system/color/lightThemeColors.kt
  design_system/src/main/java/com/cairosquad/design_system/component/TopBar.kt
Labels: component

#16 component/movie-card
  design_system/build.gradle.kts
  design_system/src/main/java/com/cairosquad/design_system/component/MovieCard.kt
  design_system/src/main/res/drawable/girl.png
  design_system/src/main/res/drawable/movie_card_img.png
  design_system/src/main/res/drawable/spider.png
  design_system/src/main/res/drawable/star.xml
  design_system/src/main/res/values-ar/strings.xml
  design_system/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  ui/src/main/res/values-ar/strings.xml
  ui/src/main/res/values/strings.xml
Labels: component

#41 feature: api key secret
  gradle/libs.versions.toml
  remote/build.gradle.kts
  remote/src/main/AndroidManifest.xml
  remote/src/main/java/com/cairosquad/remote/common/utils/constructUrl.kt
  secret.properties
Labels: enhancement

#29 feature/base_view_model
  .github/workflows/build-and-coverage-ci.yml
  .gitignore
  build.gradle.kts
  gradle/libs.versions.toml
  ui/build.gradle.kts
  ui/src/main/java/com/cairosquad/ui/utils/ObserveAsEvent.kt
  viewmodel/build.gradle.kts
  viewmodel/src/main/java/com/cairosquad/viewmodel/base/BaseViewModel.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/base/BaseViewModelTest.kt
Labels: feature

#43 Component: loading card
  design_system/src/main/java/com/cairosquad/design_system/color/MovioColors.kt
  design_system/src/main/java/com/cairosquad/design_system/color/darkThemeColors.kt
  design_system/src/main/java/com/cairosquad/design_system/color/lightThemeColors.kt
  design_system/src/main/java/com/cairosquad/design_system/component/LoadingArtistCard.kt
  design_system/src/main/java/com/cairosquad/design_system/component/LoadingMovieCard.kt
  design_system/src/main/java/com/cairosquad/design_system/component/TopBar.kt
  design_system/src/main/res/values-ar/strings.xml
  design_system/src/main/res/values/strings.xml
Labels: component

#50 Feature: app icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-ar/strings.xml
Labels: enhancement

#54 Feature/navigation
  app/src/main/java/com/cairosquad/movio/navigation/AppNavigation.kt
  app/src/main/java/com/cairosquad/movio/navigation/Routes.kt
  app/src/main/res/values/themes.xml
  build.gradle.kts
  design_system/build.gradle.kts
  design_system/src/main/java/com/cairosquad/design_system/component/MovieCard.kt
  design_system/src/main/java/com/cairosquad/design_system/component/NavigationBar.kt
  design_system/src/main/java/com/cairosquad/design_system/component/Scaffold.kt
  design_system/src/main/java/com/cairosquad/design_system/component/SectionHeader.kt
  design_system/src/main/java/com/cairosquad/design_system/component/SwitchToStartButton.kt
  design_system/src/main/res/drawable/arrow.xml
  design_system/src/main/res/drawable/arrow1.png
  design_system/src/main/res/drawable/grid.xml
  design_system/src/main/res/values-ar/strings.xml
  design_system/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  ui/src/main/java/com/cairosquad/ui/AppScreen.kt
  ui/src/main/java/com/cairosquad/ui/home/HomeScreen.kt
  ui/src/main/java/com/cairosquad/ui/library/LibraryScreen.kt
  ui/src/main/java/com/cairosquad/ui/more/MoreScreen.kt
  ui/src/main/java/com/cairosquad/ui/search/ExploreScreenContent .kt
  ui/src/main/java/com/cairosquad/ui/search/SearchScreen.kt
  ui/src/main/java/com/cairosquad/ui/splash/SplashScreen.kt
Labels: enhancement

#68 refactor : add animation for tabs
  design_system/src/main/java/com/cairosquad/design_system/component/TopBar.kt
Labels: enhancement

#99 refactor: rename SearchUiState to SearchScreenState
  ui/src/main/java/com/cairosquad/ui/search/content/ExploreScreenContent.kt
  ui/src/main/java/com/cairosquad/ui/search/content/SearchContent.kt
  ui/src/main/java/com/cairosquad/ui/search/content/SearchFailContent.kt
  ui/src/main/java/com/cairosquad/ui/search/content/SearchLoadingContent.kt
  ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt
  ui/src/main/java/com/cairosquad/ui/search/content/SearchScreenContent.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/searchviewmodel/SearchScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/searchviewmodel/SearchViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/searchviewmodel/mapper.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/searchviewmodel/SearchViewModelTest.kt
Labels: enhancement

#108 fix: app distribution.
  .github/workflows/cd-firebase.yml
Labels: fix

#113 refactor: rename SearchUiEvent to SearchEffect
  ui/src/main/java/com/cairosquad/ui/search/SearchScreen.kt
  ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/base/BaseViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/searchviewmodel/SearchEffect.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/searchviewmodel/SearchScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/searchviewmodel/SearchUiEvent.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/searchviewmodel/SearchViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/searchviewmodel/mapper.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/base/BaseViewModelTest.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/searchviewmodel/SearchViewModelTest.kt
Labels: enhancement

#160 fix: add RTL support to ActionBar
  ui/src/main/java/com/cairosquad/ui/movio_component/ActionBar.kt
Labels: enhancement, fix

#169 fix: restructure component imports and update package names
  design_system/src/main/java/com/cairosquad/design_system/basic_component/Chip.kt
  design_system/src/main/java/com/cairosquad/design_system/basic_component/InfoChip.kt
  design_system/src/main/java/com/cairosquad/design_system/basic_component/RefreshBox.kt
  design_system/src/main/res/values-ar/strings.xml
  ui/src/main/java/com/cairosquad/ui/details/ArtistScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/MovieScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/ReviewsScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SeasonScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SeasonsScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SeriesScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SimilarMoviesScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SimilarSeriesScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/TopCastScreen.kt
  ui/src/main/java/com/cairosquad/ui/search/ForYouScreen.kt
  ui/src/main/java/com/cairosquad/ui/search/content/SearchScreenContent.kt
  ui/src/main/res/values-ar/strings.xml
  ui/src/main/res/values/strings.xml
Labels: enhancement, fix

#167 fix: rename TopBar to TabRow
  design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt
  ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt
Labels: enhancement, fix

#179 fix: move resources from UI module to design system
  design_system/src/main/res/drawable/outline_bookmark.xml
  design_system/src/main/res/drawable/outline_play.xml
  design_system/src/main/res/drawable/outline_star.xml
  design_system/src/main/res/drawable/review_star.xml
  design_system/src/main/res/values-ar/strings.xml
  design_system/src/main/res/values/strings.xml
  ui/src/main/java/com/cairosquad/ui/movio_component/ActionBar.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/MovieCard.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/ReviewCard.kt
  ui/src/main/res/values-ar/strings.xml
  ui/src/main/res/values/strings.xml
Labels: enhancement

#178 Refactor/combine repo separated interfaces
  app/src/main/java/com/cairosquad/movio/di/domainModule.kt
  app/src/main/java/com/cairosquad/movio/di/repositoryModule.kt
  domain/src/main/java/com/cairosquad/domain/exception/exception.kt
  domain/src/main/java/com/cairosquad/domain/repository/ArtistsRepository.kt
  domain/src/main/java/com/cairosquad/domain/repository/MoviesRepository.kt
  domain/src/main/java/com/cairosquad/domain/repository/SearchRepository.kt
  domain/src/main/java/com/cairosquad/domain/repository/SeriesRepository.kt
  domain/src/main/java/com/cairosquad/domain/search/repository/DiscoveryRepository.kt
  domain/src/main/java/com/cairosquad/domain/search/repository/SearchHistoryRepository.kt
  domain/src/main/java/com/cairosquad/domain/search/usecase/ClearSearchHistoryUseCase.kt
  domain/src/main/java/com/cairosquad/domain/search/usecase/GetArtistDetailsUseCase.kt
  domain/src/main/java/com/cairosquad/domain/search/usecase/GetLocalSearchHistoryUseCase.kt
  domain/src/main/java/com/cairosquad/domain/search/usecase/GetMoviesDetailsUseCase.kt
  domain/src/main/java/com/cairosquad/domain/search/usecase/GetPersonalizedMoviesUseCase.kt
  domain/src/main/java/com/cairosquad/domain/search/usecase/GetSuggestedMoviesUseCase.kt
  domain/src/main/java/com/cairosquad/domain/usecase/artists/GetArtistDetailsUseCase.kt
  domain/src/main/java/com/cairosquad/domain/usecase/movies/GetMoviesDetailsUseCase.kt
  domain/src/main/java/com/cairosquad/domain/usecase/movies/GetPersonalizedMoviesUseCase.kt
  domain/src/main/java/com/cairosquad/domain/usecase/movies/GetSuggestedMoviesUseCase.kt
  domain/src/main/java/com/cairosquad/domain/usecase/search/ClearSearchHistoryUseCase.kt
  domain/src/main/java/com/cairosquad/domain/usecase/search/GetLocalSearchHistoryUseCase.kt
  domain/src/main/java/com/cairosquad/domain/usecase/search/SearchUseCase.kt
  domain/src/main/java/com/cairosquad/domain/usecase/series/GetSeriesDetailsUseCase.kt
  domain/src/test/java/com/cairosquad/domain/usecase/ClearSearchHistoryUseCaseTest.kt
  domain/src/test/java/com/cairosquad/domain/usecase/GetLocalSearchHistoryUseCaseTest.kt
  domain/src/test/java/com/cairosquad/domain/usecase/GetPersonalizedMoviesUseCaseTest.kt
  domain/src/test/java/com/cairosquad/domain/usecase/GetSuggestedMoviesUseCaseTest.kt
  domain/src/test/java/com/cairosquad/domain/usecase/SearchUseCaseTest.kt
  repository/src/main/java/com/cairosquad/repository/common/exception/mapper.kt
  repository/src/main/java/com/cairosquad/repository/search/LocalRecentSearchRepositoryImpl.kt
  repository/src/main/java/com/cairosquad/repository/search/MoviesRepositoryImpl.kt
  repository/src/main/java/com/cairosquad/repository/search/SearchRepositoryImpl.kt
  repository/src/test/java/com/cairosquad/repository/search/RecentSearchRepositoryImplTest.kt
  repository/src/test/java/com/cairosquad/repository/search/RecommendationRepositoryImplTest.kt
  repository/src/test/java/com/cairosquad/repository/search/SearchRepositoryImplTest.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/exception/exceptionToErrorStatus.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchViewModel.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/searchviewmodel/SearchViewModelTest.kt
Labels: enhancement, fix

#180 fix: rename events parameter to effects in ObserveAsEffect
  ui/src/main/java/com/cairosquad/ui/search/SearchScreen.kt
  ui/src/main/java/com/cairosquad/ui/utils/ObserveAsEffect.kt
Labels: enhancement, fix

#171 fix: rename common package to utils for MovioDataBase
  app/src/main/java/com/cairosquad/movio/di/localDataSourceModule.kt
  local/src/main/java/com/cairosquad/local/utils/MovioDataBase.kt
Labels: enhancement, fix

#230 fix : rename common package to utils in repository
  local/src/main/java/com/cairosquad/local/search/discovery/DiscoveryDataSourceImpl.kt
  remote/src/main/java/com/cairosquad/remote/utils/callApi.kt
  remote/src/main/java/com/cairosquad/remote/utils/responseToException.kt
  repository/src/main/java/com/cairosquad/repository/search/MoviesRepositoryImpl.kt
  repository/src/main/java/com/cairosquad/repository/search/SearchRepositoryImpl.kt
  repository/src/main/java/com/cairosquad/repository/utils/exception/DataSourceExceptions.kt
  repository/src/main/java/com/cairosquad/repository/utils/mappers/DataToDomainExceptionMapper.kt
  repository/src/main/java/com/cairosquad/repository/utils/mappers/DiscoveryMapper.kt
Labels: enhancement, fix

#237 Fix/standardize package paths across files
  app/src/main/java/com/cairosquad/movio/di/localDataSourceModule.kt
  design_system/src/main/java/com/cairosquad/design_system/basic_component/BottomSheet.kt
  design_system/src/main/java/com/cairosquad/design_system/basic_component/NavigationBar.kt
  design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt
  domain/src/test/java/com/cairosquad/domain/usecase/GetLocalSearchHistoryUseCaseTest.kt
  domain/src/test/java/com/cairosquad/domain/usecase/GetPersonalizedMoviesUseCaseTest.kt
  domain/src/test/java/com/cairosquad/domain/usecase/GetSuggestedMoviesUseCaseTest.kt
  domain/src/test/java/com/cairosquad/domain/usecase/SearchUseCaseTest.kt
  local/src/main/java/com/cairosquad/local/search/cache/CacheDataSourceImpl.kt
  local/src/test/java/com/cairosquad/local/cache/LocalSearchCacheDataSourceImplTest.kt
  local/src/test/java/com/cairosquad/local/recent/LocalRecentSearchDataSourceImplTest.kt
  repository/src/test/java/com/cairosquad/repository/search/SearchRepositoryImplTest.kt
  safe_image_viewer/src/main/java/com/cairosquad/safe_image_viewer/safe_image_viewer/SafeImageViewer.kt
  ui/src/main/java/com/cairosquad/ui/details/SeriesScreen.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/ReviewCard.kt
  ui/src/main/java/com/cairosquad/ui/splash/SplashScreen.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchUiState.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/base/BaseViewModelTest.kt
Labels: enhancement, fix

#240 Feature/artist details screen
  app/src/main/java/com/cairosquad/movio/di/viewModelModule.kt
  app/src/test/java/com/cairosquad/viewmodel/details/artist/ArtistViewModelTest.kt
  design_system/src/main/java/com/cairosquad/design_system/basic_component/ExpandableText.kt
  design_system/src/main/java/com/cairosquad/design_system/modifier/CustomBrush.kt
  design_system/src/main/res/drawable/component_1.xml
  design_system/src/main/res/values-ar/strings.xml
  design_system/src/main/res/values/strings.xml
  ui/src/main/java/com/cairosquad/ui/details/ArtistScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/artist/ArtistScreen.kt
  ui/src/main/java/com/cairosquad/ui/navigation/AppNavigation.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/artist/ArtistEffect.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/artist/ArtistInteractionListener.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/artist/ArtistScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/artist/ArtistViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/artist/mapper.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/ss.java
  viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchViewModel.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/artistviewmodel/ArtistUiStateMapperTest.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/artistviewmodel/ArtistViewModelTest.kt
Labels: Done

#251 Refactor/reviews view model
  ui/src/main/java/com/cairosquad/ui/details/ReviewsScreen.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/LoadingReviewCard.kt
  ui/src/main/java/com/cairosquad/ui/navigation/AppNavigation.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/reviews/ReviewsEffect.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/reviews/ReviewsInteractionListener.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/reviews/ReviewsViewModel.kt
Labels: enhancement

#248 Feature/similar movies screen
  app/src/main/java/com/cairosquad/movio/di/viewModelModule.kt
  design_system/src/main/res/values-ar/strings.xml
  design_system/src/main/res/values/strings.xml
  ui/src/main/java/com/cairosquad/ui/details/SimilarMoviesScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/similar_movies/SimilarMoviesScreen.kt
  ui/src/main/java/com/cairosquad/ui/navigation/AppNavigation.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/similar_movies/Mapper.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/similar_movies/SimilarMoviesEffect.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/similar_movies/SimilarMoviesInteractionListener.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/similar_movies/SimilarMoviesScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/similar_movies/SimilarMoviesViewModel.kt
Labels: Done

#239 Feat/episodes details screen
  app/src/main/java/com/cairosquad/movio/di/viewModelModule.kt
  design_system/src/main/java/com/cairosquad/design_system/basic_component/AppDropDownMenu.kt
  design_system/src/main/res/drawable/drop_down_arrow.xml
  domain/src/test/java/com/cairosquad/domain/usecase/series/GetSeriesDetailsUseCaseTest.kt
  entity/src/main/java/com/cairosquad/entity/Episode.kt
  repository/src/main/java/com/cairosquad/repository/details/SeriesRepositoryImpl.kt
  repository/src/main/java/com/cairosquad/repository/series/SeriesRepositoryImpl.kt
  repository/src/main/java/com/cairosquad/repository/series/data_source/remote/dto/EpisodeRemoteDto.kt
  repository/src/main/java/com/cairosquad/repository/series/data_source/remote/dto/SeasonRemoteDto.kt
  ui/src/main/java/com/cairosquad/ui/AppScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/EpisodeScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/EpisodesScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SeasonsScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SeriesScreen.kt
  ui/src/main/java/com/cairosquad/ui/navigation/AppNavigation.kt
  ui/src/main/java/com/cairosquad/ui/navigation/Routes.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/episodes/EpisodesDetailEffect.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/episodes/EpisodesDetailsInteractionListener.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/episodes/EpisodesDetailsScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/episodes/EpisodesDetailsViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/episodes/mapper.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/series/mapper.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/series/season/SeasonDetailEffect.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/series/season/SeasonDetailsInteractionListener.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/series/season/SeasonDetailsScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/series/season/SeasonsViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchViewModel.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/details/series/season/SeasonViewModelTest.kt
Labels: Need Changes

#266 Refactor/UI module
  design_system/src/main/java/com/cairosquad/design_system/basic_component/AppDropDownMenu.kt
  design_system/src/main/java/com/cairosquad/design_system/basic_component/Icon.kt
  design_system/src/main/java/com/cairosquad/design_system/basic_component/Text.kt
  ui/build.gradle.kts
  ui/src/main/java/com/cairosquad/ui/details/MovieScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SeriesScreen.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/ActionBar.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/ArtistCard.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/LoginBottomSheet.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/MovieCard.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/ReviewCard.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/SeasonCard.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/SeasonScreenCard.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/SectionHeader.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/ShareBottomSheet.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/SmallAristCard.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/StateMessage.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/SwitchToStartButton.kt
Labels: Refactor

#295 feat : create categories chips component
  design_system/src/main/java/com/cairosquad/design_system/basic_component/Chip.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/CategoriesChips.kt
Labels: component

#311 Feature/login viewmodel
  app/src/main/java/com/cairosquad/movio/di/domainModule.kt
  domain/src/main/java/com/cairosquad/domain/usecase/authentication/LoginUseCase.kt
  local/schemas/com.cairosquad.local.utils.MovioDataBase/1.json
  viewmodel/build.gradle.kts
  viewmodel/src/main/java/com/cairosquad/viewmodel/login/LoginScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/login/LoginViewModel.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/login/LoginViewModelTest.kt
Labels: feature

#309 Feature/log in screen
  design_system/build.gradle.kts
  design_system/src/main/java/com/cairosquad/design_system/basic_component/Button.kt
  design_system/src/main/res/raw/spinner.json
  gradle/libs.versions.toml
  ui/src/main/java/com/cairosquad/ui/login/LoginScreen.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/LoginScreenHeader.kt
  ui/src/main/res/drawable/close_eye.xml
  ui/src/main/res/drawable/eye.xml
  ui/src/main/res/drawable/info_circle.xml
  ui/src/main/res/drawable/lock.xml
  ui/src/main/res/drawable/profile_login.xml
  ui/src/main/res/drawable/welcome_icon.xml
  ui/src/main/res/values-ar/strings.xml
  ui/src/main/res/values/strings.xml
  viewmodel/src/main/java/com/cairosquad/viewmodel/login/LoginScreenState.kt
Labels: enhancement, feature, component

#339 Fix/home see all loading status
  ui/src/main/java/com/cairosquad/ui/see_all_screen/SeeAllLoadingScreen.kt
  ui/src/main/java/com/cairosquad/ui/see_all_screen/SeeAllScreen.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/see_all/SeeAllScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/see_all/SeeAllViewModel.kt
Labels: Done

#337 Refactor/make app view model consistent
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/artist/ArtistViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/episodes/EpisodesDetailsViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/top_cast/TopCastViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/foryou/ForYouViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchViewModel.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/searchviewmodel/SearchViewModelTest.kt
Labels: Done

#277 Feature/default values
  ui/src/main/java/com/cairosquad/ui/details/MovieScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SeriesScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/artist/ArtistScreen.kt
Labels: Done

#340 Refactor/mappers
  local/src/main/java/com/cairosquad/local/search/discovery/DiscoveryDataSourceImpl.kt
  repository/src/main/java/com/cairosquad/repository/artists/ArtistsRepositoryImpl.kt
  repository/src/main/java/com/cairosquad/repository/artists/mapper.kt
  repository/src/main/java/com/cairosquad/repository/movie/MovieRepositoryImpl.kt
  repository/src/main/java/com/cairosquad/repository/search/SearchRepositoryImpl.kt
  repository/src/main/java/com/cairosquad/repository/search/data_source/local/dto/CacheDtoMappers.kt
  repository/src/main/java/com/cairosquad/repository/utils/mappers/DiscoveryMapper.kt
  repository/src/test/java/com/cairosquad/repository/artists/ArtistsRepositoryImplTest.kt
  repository/src/test/java/com/cairosquad/repository/search/EntityCacheMapperTest.kt
  repository/src/test/java/com/cairosquad/repository/utils/mappers/MovieCacheDtoExtensionsTest.kt
Labels: enhancement, Refactor

#371 refactor: version catalog
  gradle/libs.versions.toml
  local/build.gradle.kts
  repository/build.gradle.kts
Labels: Refactor

#375 fix/details
  app/src/main/java/com/cairosquad/movio/di/viewModelModule.kt
  design_system/src/main/res/values-ar/strings.xml
  design_system/src/main/res/values/strings.xml
  ui/src/main/java/com/cairosquad/ui/details/MovieScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SeriesScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/artist/ArtistScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/similar_movies/SimilarMoviesScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/similar_series/SimilarSeriesScreen.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/ReviewCard.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/bottom_sheet/ListBottomSheet.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/bottom_sheet/LoginBottomSheet.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/artist/ArtistEffect.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/artist/ArtistInteractionListener.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/artist/ArtistViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/movie/MovieEffect.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/movie/MovieInteractionListener.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/movie/MovieScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/movie/MovieViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/series/SeriesDetailEffect.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/series/SeriesDetailsInteractionListener.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/series/SeriesDetailsScreenState.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/details/series/SeriesDetailsViewModel.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/details/movie/MovieViewModelTest.kt
  viewmodel/src/test/java/com/cairosquad/viewmodel/details/series/SeriesDetailsViewModelTest.kt
Labels: Refactor

#351 Move combineTwoList into ListUtil utility file
  viewmodel/src/main/java/com/cairosquad/viewmodel/home/HomeViewModel.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/util/ListUtil.kt
Labels: Done

#376 fix: add error handling
  ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchInteractionListener.kt
  viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchViewModel.kt
Labels: bug, fix, Refactor

#414 fix: #68 bug placeholder for review card pfp.
  ui/src/main/java/com/cairosquad/ui/details/composable/ReviewSection.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/ReviewCard.kt
Labels: fix

#429 16 - when make size larger
  ui/src/main/java/com/cairosquad/ui/auth/LoginScreen.kt
Labels: bug

#441 fix: bug102: make bookmark text alignmernt center with the icon
  design_system/src/main/java/com/cairosquad/design_system/basic_component/Text.kt
  ui/src/main/java/com/cairosquad/ui/movio_component/ActionBar.kt
Labels: bug

#444 fix: make expandable text use read more and read less instead of more…
  ui/src/main/java/com/cairosquad/ui/details/MovieScreen.kt
  ui/src/main/java/com/cairosquad/ui/details/SeriesScreen.kt
  ui/src/main/res/values-ar/strings.xml
  ui/src/main/res/values/strings.xml
Labels: bug, fix

#468 Restrict WebView navigation to themoviedb.org
  design_system/src/main/java/com/cairosquad/design_system/basic_component/WebView.kt
Labels: fix
